### ISSUE TITLE
looking forward to pretrained models！

### ISSUE THREAD

**Issue by lunalulu** [Nioolek/PPYOLOE_pytorch#2] opened 2022-04-28 07:23 UTC

**Comment by miemie2013** [comment] 2022-05-16 10:16
> _No description provided._

Hi! You can train COCO2017 from scratch with my codes https://github.com/miemie2013/miemiedetection 

just input these commands:
```
wget https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams
python tools/convert_weights.py -f exps/ppyoloe/ppyoloe_crn_s_300e_coco.py -c CSPResNetb_s_pretrained.pdparams -oc CSPResNetb_s_pretrained.pth -nc 80 --only_backbone True
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python tools/train.py -f exps/ppyoloe/ppyoloe_crn_s_300e_coco.py -d 8 -b 256 -eb 16 -c CSPResNetb_s_pretrained.pth --fp16
```

Please refer to https://github.com/miemie2013/miemiedetection/blob/main/docs/README_PPYOLO.md for more details.

**Comment by Nioolek** [comment] 2022-05-16 10:39
I will update tomorrow

**Comment by Nioolek** [comment] 2022-05-17 03:31
> _No description provided._

The pretrained model has been uploaded.And the code can reproduce the mAP result on COCO, please use it.

**Comment by Nioolek** [comment] 2022-05-27 03:37
Because the pretrained model has been uploaded, I am now closing the issue. If you have any questions, you can reopen it.

**Closed by Nioolek** 2022-05-27 03:37 UTC
